// <auto-generated />
namespace ShoppingCartServiceLibrary.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203121915338_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVZzW7jNhC+F+g7CDq1BdZyUmCxG9i7SJ2kCLr5aeTuNaClsU2UIlWSMuxn20Mfqa/Qoax/yrLsZNMNeospzjfD4TfDmck/X/4efVxHzFmBVFTwsXsyGLoO8ECElC/GbqLnb965Hz98/93oMozWzud836nZh5Jcjd2l1vGZ56lgCRFRg4gGUigx14NARB4JhXc6HL7zToYeIISLWI4zeki4phGkP/DnRPAAYp0QdiNCYCpbxy9+iurckghUTAIYu/5SxDFaNyFS+yBXNIBPdCaJ3LjOOaMELfKBzQ80b/jemOcWilH1JZqoN9NNDKn6uubqTtz7G2xqC7h0L0UMUm8eYN4ifx26jlfH8JogBcQOeWPa2L3m+udT17lNGCMzhgtzwhS4Tvz2zNdCwq/AQRIN4T3RGiRe3nUI6dEyF53Fb/t56b03PDVe8gjnQhONTLAO0TB5IsGozm29wB9TvPcWc7txkBZ0To8BuiUrukhtbZpmvKghUq7zACzdoZY03rJnkH99rF26cyVF9CBYRby24XFK5AJw31R07fJFIoOGqSOv5FsnC3PIYxiYyx7DvqrsK2DeYcHSjZW6O0PwtURUZAJdQ/gJ+EIvC5Qbss5X8E/X+YNTzKQopGVSo+r2d7fS3xOS+eoppt9LapiWRY1IUPJgjG84iOvR+XxxnEdodxzn0d4njs+VEgFNzWsE1GPHu3LJQ6eXnVtuVk+MdEyYpjGjAZozdn+yvLoPvEhmJXjdi3UFJ24zAd3xC2CgwTkPdFo2TIgKSGjfL/osrK9gzgJpkgVhWBwoLQnl2k5wlAc0JqzPMRrCR7zQxtBCZfPLBcTATXrrc1/PY0uhsuHMfb4beRUy2m8NymiUANliiPkGa5ulRs4H3SKBz2sZEK0sslhZB6u80xZQyfUGSOWANlIjF1T2diaNpv/7xmZxoNpZrOvsG40VuIafm0FVd0JLjipuuqy3vW3BnRfm3o7KfHRDUs2VSj1bcfxtmT554x9egkdbDC9QLZV4YW2hCYsMsoDGV1SNll5RqTQ+MGRGzHsyCSNr2wG8zjW20du+x5ykuZT525as9y6DLqqV3r3CA0cmyaQF1g4q2OJpI0UYkXuKpIlgScT75Z/dqEW9UIUrFvvjlPVCFahctZFGXsNPVs60bsd6iOpX3osQZVg/Exnaa/xeRNgtuvO6KoV97cZ2NgsvT6ltkq9itaX9LoSynK6ilKv9kbKSugqTLf3vQ8R6WJpbCu3FA9N4SEZZUt8/B7Ky/HaL66CLVjRMM/xGIUsGZsPA/4tNGMXzlhtuCKdzUHoq/gQz08JH6PgRUtGiKhWy1zhHosY1e/v2p7WOIf7Qz9E69gR6hUOVr3INHTf+hFEIXxEZLIn8ISLrH5863jjGmNpwY84EORziGyXoU6cF9Q7nv2jg7XbmyCnFUZOAPdX0i3T+r6vLt5um/j3+3hZ/+zRjVMwEsmAbDd3N664pQOcQoE3Nzpb7hWcEbf6yO7c+Y4HWicLX6f7tYgx5V/nXHXJf0UUJYf6RxyGoMa7Yc83nIg+AhkX5lmZSBU0wkZJzqemcBBo/B6BUOn//TFiCWy6jGYTX/C7RcaLxyBDNWK2aNwHUpT8dcdRtHt3F6RT5OY6AZlLzFtzxXxLKwsLuq5a3YAeEicysFjB3qU1NsNgUSLeC9wTK3FcklClEMUMwdcd9soLdtu33Yd1jowtKFpJEVQ9uV/LkQVBzRQUqqEqU+vAn0jWM1h/+BbTxH+SsHgAA"; }
        }
    }
}
