//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxy.IRyanService")]
    public interface IRyanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRyanService/getWsOperations", ReplyAction="http://tempuri.org/IRyanService/getWsOperationsResponse")]
        string[] getWsOperations(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRyanService/WsHashOperations", ReplyAction="http://tempuri.org/IRyanService/WsHashOperationsResponse")]
        System.Collections.Generic.Dictionary<object, object> WsHashOperations(string wsdlUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRyanServiceChannel : WebClient.ServiceProxy.IRyanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RyanServiceClient : System.ServiceModel.ClientBase<WebClient.ServiceProxy.IRyanService>, WebClient.ServiceProxy.IRyanService {
        
        public RyanServiceClient() {
        }
        
        public RyanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RyanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RyanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RyanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getWsOperations(string url) {
            return base.Channel.getWsOperations(url);
        }
        
        public System.Collections.Generic.Dictionary<object, object> WsHashOperations(string wsdlUrl) {
            return base.Channel.WsHashOperations(wsdlUrl);
        }
    }
}
