//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StemmingServiceWebApplication.StemmingServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StemmingServiceProxy.IStemmingService")]
    public interface IStemmingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStemmingService/Stemming", ReplyAction="http://tempuri.org/IStemmingService/StemmingResponse")]
        string Stemming(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStemmingServiceChannel : StemmingServiceWebApplication.StemmingServiceProxy.IStemmingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StemmingServiceClient : System.ServiceModel.ClientBase<StemmingServiceWebApplication.StemmingServiceProxy.IStemmingService>, StemmingServiceWebApplication.StemmingServiceProxy.IStemmingService {
        
        public StemmingServiceClient() {
        }
        
        public StemmingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StemmingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StemmingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StemmingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Stemming(string str) {
            return base.Channel.Stemming(str);
        }
    }
}
