//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top10ContentWordsWebApplication.Top10ContentWordsServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Top10ContentWordsServiceProxy.ITop10ContentWordsService")]
    public interface ITop10ContentWordsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITop10ContentWordsService/Top10ContentWords", ReplyAction="http://tempuri.org/ITop10ContentWordsService/Top10ContentWordsResponse")]
        string[] Top10ContentWords(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITop10ContentWordsServiceChannel : Top10ContentWordsWebApplication.Top10ContentWordsServiceProxy.ITop10ContentWordsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Top10ContentWordsServiceClient : System.ServiceModel.ClientBase<Top10ContentWordsWebApplication.Top10ContentWordsServiceProxy.ITop10ContentWordsService>, Top10ContentWordsWebApplication.Top10ContentWordsServiceProxy.ITop10ContentWordsService {
        
        public Top10ContentWordsServiceClient() {
        }
        
        public Top10ContentWordsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Top10ContentWordsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Top10ContentWordsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Top10ContentWordsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Top10ContentWords(string url) {
            return base.Channel.Top10ContentWords(url);
        }
    }
}
