//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.reqdServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="reqdServices.IReqdServices")]
    public interface IReqdServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReqdServices/top10Words", ReplyAction="http://tempuri.org/IReqdServices/top10WordsResponse")]
        string[] top10Words(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReqdServices/wordFilter", ReplyAction="http://tempuri.org/IReqdServices/wordFilterResponse")]
        string wordFilter(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReqdServices/newsFocus", ReplyAction="http://tempuri.org/IReqdServices/newsFocusResponse")]
        string[] newsFocus(string[] topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReqdServices/getDefinition", ReplyAction="http://tempuri.org/IReqdServices/getDefinitionResponse")]
        string[] getDefinition(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReqdServicesChannel : TryIt.reqdServices.IReqdServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReqdServicesClient : System.ServiceModel.ClientBase<TryIt.reqdServices.IReqdServices>, TryIt.reqdServices.IReqdServices {
        
        public ReqdServicesClient() {
        }
        
        public ReqdServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReqdServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReqdServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReqdServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] top10Words(string url) {
            return base.Channel.top10Words(url);
        }
        
        public string wordFilter(string text) {
            return base.Channel.wordFilter(text);
        }
        
        public string[] newsFocus(string[] topics) {
            return base.Channel.newsFocus(topics);
        }
        
        public string[] getDefinition(string word) {
            return base.Channel.getDefinition(word);
        }
    }
}
