//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartServiceWebApplication.ShoppingCartServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCart", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCartServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ShoppingCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoppingCartIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoppingCartId {
            get {
                return this.ShoppingCartIdField;
            }
            set {
                if ((this.ShoppingCartIdField.Equals(value) != true)) {
                    this.ShoppingCartIdField = value;
                    this.RaisePropertyChanged("ShoppingCartId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCartServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.ShoppingCart ShoppingCartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoppingCartIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemId {
            get {
                return this.CartItemIdField;
            }
            set {
                if ((this.CartItemIdField.Equals(value) != true)) {
                    this.CartItemIdField = value;
                    this.RaisePropertyChanged("CartItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.ShoppingCart ShoppingCart {
            get {
                return this.ShoppingCartField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartField, value) != true)) {
                    this.ShoppingCartField = value;
                    this.RaisePropertyChanged("ShoppingCart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoppingCartId {
            get {
                return this.ShoppingCartIdField;
            }
            set {
                if ((this.ShoppingCartIdField.Equals(value) != true)) {
                    this.ShoppingCartIdField = value;
                    this.RaisePropertyChanged("ShoppingCartId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingCartServiceProxy.IShoppingCartService")]
    public interface IShoppingCartService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/AddItemToCart", ReplyAction="http://tempuri.org/IShoppingCartService/AddItemToCartResponse")]
        bool AddItemToCart(int shoppingCartId, string item, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ClearCart", ReplyAction="http://tempuri.org/IShoppingCartService/ClearCartResponse")]
        bool ClearCart(int shoppingCartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/CreateCart", ReplyAction="http://tempuri.org/IShoppingCartService/CreateCartResponse")]
        int CreateCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/GetCart", ReplyAction="http://tempuri.org/IShoppingCartService/GetCartResponse")]
        ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.ShoppingCart GetCart(int shoppingCartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/ModifyItemInCart", ReplyAction="http://tempuri.org/IShoppingCartService/ModifyItemInCartResponse")]
        bool ModifyItemInCart(int shoppingCartId, int cartItemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/DeleteItemFromCart", ReplyAction="http://tempuri.org/IShoppingCartService/DeleteItemFromCartResponse")]
        bool DeleteItemFromCart(int shoppingCartId, int cartItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingCartService/RemoveCart", ReplyAction="http://tempuri.org/IShoppingCartService/RemoveCartResponse")]
        bool RemoveCart(int shoppingCartId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingCartServiceChannel : ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.IShoppingCartService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingCartServiceClient : System.ServiceModel.ClientBase<ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.IShoppingCartService>, ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.IShoppingCartService {
        
        public ShoppingCartServiceClient() {
        }
        
        public ShoppingCartServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingCartServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingCartServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingCartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddItemToCart(int shoppingCartId, string item, int quantity) {
            return base.Channel.AddItemToCart(shoppingCartId, item, quantity);
        }
        
        public bool ClearCart(int shoppingCartId) {
            return base.Channel.ClearCart(shoppingCartId);
        }
        
        public int CreateCart() {
            return base.Channel.CreateCart();
        }
        
        public ShoppingCartServiceWebApplication.ShoppingCartServiceProxy.ShoppingCart GetCart(int shoppingCartId) {
            return base.Channel.GetCart(shoppingCartId);
        }
        
        public bool ModifyItemInCart(int shoppingCartId, int cartItemId, int quantity) {
            return base.Channel.ModifyItemInCart(shoppingCartId, cartItemId, quantity);
        }
        
        public bool DeleteItemFromCart(int shoppingCartId, int cartItemId) {
            return base.Channel.DeleteItemFromCart(shoppingCartId, cartItemId);
        }
        
        public bool RemoveCart(int shoppingCartId) {
            return base.Channel.RemoveCart(shoppingCartId);
        }
    }
}
